on:
  workflow_call:

jobs:
  build_test_lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build and test
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Linting check
        run: npm run lint

      - name: Run tests
        run: npm run test
